languageCode = "en-us"
title = "Auggie Heschmeyer"
baseURL = "https://auggieheschmeyer.com/"
copyright = "© Auggie Heschmeyer {year}"

# This is just to get the exampleSite to work with the theme 
# in this repository. Don't mimic this. When using the theme
# you should place it in themes/codex and list theme = "codex"
theme = "hugo-theme-codex"

[[menu.main]]
  identifier = "about"
  name = "about"
  title = "about"
  url = "/"

[[menu.main]]
  identifier = "blog"
  name = "blog"
  title = "Blog"
  url = "/blog"

preserveTaxonomyNames = true

[taxonomies]
  tag = "tags"

[params]
  instagram = "realauggieheschmeyer"
  twitter = "realauggiehesch"
  github = "realauggieheschmeyer"
